language: julia
os:
  - linux
  # - osx
julia:
  - release
  - nightly
  - 0.4
notifications:
  email: false
sudo: false
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia --check-bounds=yes --color=yes -e 'Pkg.add("LibCURL"); Pkg.checkout("LibCURL"); Pkg.clone(pwd()); Pkg.build("FTPClient"); Pkg.test("FTPClient"; coverage=true)'
after_success:
 - julia -e 'cd(Pkg.dir("FTPClient")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
